# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Weiβlogy
email: dreamfragment623+github@gmail.com
description: "作ったもの、気づいたこと、試したこと。元エンジニアの視点で技術も日常もつづる雑多ブログ「Weiβlogy」。"
logo: /assets/img/logo.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.weizlogy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twilightalpaca
github_username: weizlogy
locale: ja_JP # OGP用のロケール設定だよ！( *´꒳`*)੭⁾⁾
lang: ja-JP   # HTMLのlang属性用の設定だよ！こっちはハイフン使うのが普通なんだ！(๑•̀ㅁ•́ฅ✧

# GitHub Pages の自動ビルドではデフォルトで safe モード（safe: true）です。
# safe モードではサードパーティプラグインを無効化するため、
# サイトマップが生成されないことがあります。
safe: false

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap 

excerpt_separator: "<!--more-->"

# test
## bundle exec jekyll serve

defaults:
  - scope:
      path: ""
    values:
      sitemap: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - google179db5509b498a97.html
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
